{{- define "defaultGateway.gateway" -}}
{{- $name := (index . 1) }}
{{- $spec := (index . 2) }}
{{- with (first .) }}
{{- $gatewaySettings := $spec.gatewaySettings }}
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: {{ $name | kebabcase }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
spec:
  {{- if $gatewaySettings.ipv4Only }}
  bindAddress: "0.0.0.0"
  {{- else }}
  bindAddress: "::"
  {{- end }}
  bindPort: {{ $spec.podTemplate.httpPort }}
  httpGateway:
    virtualServiceNamespaces:
      - {{ .Release.Namespace }}
    options:
      ratelimitServer:
        ratelimitServerRef:
          name: ratelimit
          namespace: {{ .Release.Namespace }}
      extauth:
        extauthzServerRef:
          name: extauth
          namespace: {{ .Release.Namespace }}
{{ if or ($gatewaySettings.options) ($gatewaySettings.accessLoggingService) }}
  options:
{{- end }}
  {{- if $gatewaySettings.options }}
  {{ toYaml $gatewaySettings.options | nindent 6 }}
  {{- end }}
  {{- if $gatewaySettings.accessLoggingService }}
    accessLoggingService:
  {{ toYaml $gatewaySettings.accessLoggingService | nindent 6 }}
  {{- end }}
  useProxyProto: {{ $gatewaySettings.useProxyProto }}
  ssl: false
  proxyNames:
  - {{ .Release.Namespace }}-{{ $name | kebabcase }}
{{- end }}{{/* with */}}
{{- end }}{{/* define "defaultGateway.gateway" */}}


{{- define "defaultGateway.sslGateway" -}}
{{- $name := (index . 1) }}
{{- $spec := (index . 2) }}
{{- with (first .) }}
{{- $gatewaySettings := $spec.gatewaySettings }}
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: {{ $name | kebabcase }}-ssl
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
spec:
  {{- if $gatewaySettings.ipv4Only }}
  bindAddress: "0.0.0.0"
  {{- else }}
  bindAddress: "::"
  {{- end }}
  bindPort: {{ $spec.podTemplate.httpsPort }}
  httpGateway:
    virtualServiceNamespaces:
      - {{ .Release.Namespace }}
    options:
      ratelimitServer:
        ratelimitServerRef:
          name: ratelimit
          namespace: {{ .Release.Namespace }}
      extauth:
        extauthzServerRef:
          name: extauth
          namespace: {{ .Release.Namespace }}
{{ if or ($gatewaySettings.options) ($gatewaySettings.accessLoggingService) }}
  options:
{{- end }}
  {{- if $gatewaySettings.options }}
  {{ toYaml $gatewaySettings.options | nindent 6 }}
  {{- end }}
  {{- if $gatewaySettings.accessLoggingService }}
    accessLoggingService:
  {{ toYaml $gatewaySettings.accessLoggingService | nindent 6 }}
  {{- end }}
  useProxyProto: {{ $gatewaySettings.useProxyProto }}
  ssl: true
  proxyNames:
  - {{ .Release.Namespace }}-{{ $name | kebabcase }}
{{- end }}{{/* with */}}
{{- end }}{{/* define "defaultGatway.sslGateway" */}}

{{- define "defaultGateway.failoverGateway" -}}
{{- $name := (index . 1) }}
{{- $spec := (index . 2) }}
{{- with (first .) }}
{{- $gatewaySettings := $spec.gatewaySettings }}
apiVersion: gateway.solo.io/v1
kind: Gateway
metadata:
  name: {{ $name | kebabcase }}-failover
  namespace: {{ .Release.Namespace }}
  labels:
    app: gloo
spec:
{{- if $gatewaySettings.ipv4Only }}
  bindAddress: "0.0.0.0"
{{- else }}
  bindAddress: "::"
{{- end }}
  bindPort: {{ $spec.failover.port }}
  tcpGateway:
    tcpHosts:
    - name: failover
      sslConfig:
        secretRef:
          name: {{ $spec.failover.secretName }}
          namespace: {{ .Release.Namespace }}
      destination:
        forwardSniClusterName: {}
  proxyNames:
  - {{ .Release.Namespace }}-{{ $name | kebabcase }}
{{- end }}{{/* with */}}
{{- end }}{{/* define "defaultGateway.failoverGateway" */}}

{{- $gatewayProxy := .Values.gatewayProxies.gatewayProxy }}
{{- range $name, $gatewaySpec := .Values.gatewayProxies }}
{{- $spec := deepCopy $gatewaySpec | mergeOverwrite (deepCopy $gatewayProxy ) -}}
{{- $gatewaySettings := $spec.gatewaySettings }}
{{- if and $spec.gatewaySettings (not $gatewaySpec.disabled) }}
{{- $ctx := (list $ $name $spec)}}
{{- if not $gatewaySettings.disableGeneratedGateways }}
{{- if not $gatewaySettings.disableHttpGateway }}
{{- $defaultGatewayOverride := $spec.gatewaySettings.httpGatewayKubeOverride }}
---
{{- include "gloo.util.merge" (list $ctx $defaultGatewayOverride "defaultGateway.gateway") -}}
{{- end }}{{/* if not $gatewaySettings.disableHttpGateway */}}
{{- if not $gatewaySettings.disableHttpsGateway }}
{{- $sslGatewayOverride := $spec.gatewaySettings.httpsGatewayKubeOverride }}
---
{{- include "gloo.util.merge" (list $ctx $sslGatewayOverride "defaultGateway.sslGateway") -}}
{{- end }}{{/* if not $gatewaySettings.disableHttpsGateway  */}}
{{- end }}{{/* if not $gatewaySettings.disableGeneratedGateways */}}
{{- if $spec.failover }}
{{- if $spec.failover.enabled }}
{{- $failoverGatewayOverride := $spec.failover.kubeResourceOverride }}
---
{{- include "gloo.util.merge" (list $ctx $failoverGatewayOverride "defaultGateway.failoverGateway") -}}
{{- end }}{{/* if $spec.failover.enabled */}}
{{- end }}{{/* if $spec.failover */}}
{{- end }}{{/* if $spec.gatewaySettings and (not $spec.disabled) */}}
{{- end }}{{/* range gateways */}}
